# Generated by Django 4.2.4 on 2023-08-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_username_field_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('status', models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('inactive', 'Inactive')], max_length=255, null=True, verbose_name='Status of Lead')),
                ('source', models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('website', 'Website'), ('email', 'Email')], max_length=255, null=True, verbose_name='Source of Lead')),
                ('dnc', models.BooleanField(default=False, verbose_name='Do Not Call')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.userprofile',),
        ),
    ]
