# Generated by Django 4.2.4 on 2023-08-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('agent_type', models.CharField(blank=True, choices=[('recruitment', 'Recruitment'), ('retention', 'Retention'), ('reactivation', 'Reactivation')], max_length=255, null=True, verbose_name='Agent Type')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.userprofile',),
        ),
    ]
