# Generated by Django 4.2.4 on 2023-08-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.userprofile',),
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.userprofile')),
                ('is_superadmin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.userprofile',),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='isActive',
        ),
        migrations.AddField(
            model_name='customer',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
